In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [2]:
X = np.array([3.1,  54.2,  18.1, -44.9])
y = np.array([37.58, 129.56,  64.58, -48.82])

# Converting Celcius to Farenheit

In [3]:
y.shape

(4,)

In [4]:
X.shape

(4,)

In [5]:
X = X.reshape(4,1)

In [6]:
X

array([[  3.1],
       [ 54.2],
       [ 18.1],
       [-44.9]])

In [7]:
model = LinearRegression().fit(X,y)

In [8]:
model.coef_, model.intercept_

(array([1.8]), 31.999999999999993)

In [9]:
model.predict([[310.5]])

array([590.9])